### ISSUE TITLE
IDE's para empezar

### ISSUE THREAD

**Issue by SolKuczala** [comunidadit-villacrespo/site#14]
Quizas los ingresantes puedan obtener info sobre las IDE's que pueden usar, pros y contras, o al menos que le ofrece cada IDE, siendo que tienen tiempo hasta que empiezan a escribir en el editor.

**Comment by SolKuczala** [comment]
Voy a hacer un reasearch, por lo que va a tomar un tiempito, pero dale.

**Comment by NormanPerrin** [comment]
Buena iniciativa! Cualquier cosa preguntá.

**Comment by SolKuczala** [comment]
Vamo'! lastima que quedo el nombre del commit 'sin imagenes' jeje. Pero great :)

**Comment by NormanPerrin** [comment]
Ahí corregí el mensaje!
